# Generated by Django 4.2.16 on 2026-09-24 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screening', '0001_initial'),
        ('risk_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_nutrition', models.JSONField(default=dict, help_text='Objectifs et conseils nutritionnels structurés', verbose_name='recommandations nutritionnelles')),
                ('plan_activite', models.JSONField(default=dict, help_text="Objectifs d'activité physique adaptés au risque", verbose_name="programme d'activité physique")),
                ('notes_nutritionniste', models.TextField(blank=True, verbose_name='notes et observations du nutritionniste')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon (en attente de validation)'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], db_index=True, default='BROUILLON', max_length=20, verbose_name='statut de validation')),
                ('motif_rejet', models.TextField(blank=True, help_text='Raison spécifiée par le nutritionniste en cas de rejet', verbose_name='motif de rejet')),
                ('genere_le', models.DateTimeField(auto_now_add=True, verbose_name='généré le')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('fhir_resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='identifiant FHIR CarePlan')),
                ('evaluation_risque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_soin', to='risk_engine.resultatevaluationrisque', verbose_name='évaluation de risque associée')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_soin', to='screening.profilpatient', verbose_name='patient')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_valides', to=settings.AUTH_USER_MODEL, verbose_name='validé par (nutritionniste)')),
            ],
            options={
                'verbose_name': 'plan de soin',
                'verbose_name_plural': 'plans de soins',
                'ordering': ['-genere_le'],
                'indexes': [models.Index(fields=['statut', '-genere_le'], name='care_plan_p_statut_5ebcef_idx'), models.Index(fields=['patient', 'statut'], name='care_plan_p_patient_7c278d_idx')],
            },
        ),
    ]
