# Generated by Django 4.2.16 on 2026-09-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansoin',
            name='rapport_agent',
            field=models.JSONField(blank=True, default=dict, help_text='Rapport IA complet : justification, contexte DMI, métadonnées. Exposé uniquement aux nutritionnistes. Jamais transmis au citoyen.', verbose_name='rapport complet agent hybride'),
        ),
        migrations.AddField(
            model_name='plansoin',
            name='requires_medical_referral',
            field=models.BooleanField(default=False, help_text='True si le protocole exige une consultation médicale.', verbose_name='orientation médicale requise'),
        ),
        migrations.AddField(
            model_name='plansoin',
            name='urgent_flags',
            field=models.JSONField(blank=True, default=list, verbose_name='drapeaux cliniques urgents'),
        ),
    ]
