# Generated by Django 4.2.16 on 2026-09-24 22:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilPatient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ins', models.CharField(db_index=True, help_text="Clé unique nationale d'identification du patient", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="L'INS doit comporter entre 8 et 15 caractères alphanumériques.", regex='^[A-Z0-9]{8,15}$')], verbose_name='Identifiant National de Santé (INS)')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='genre')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='numéro de téléphone')),
                ('gouvernorat', models.CharField(max_length=100, verbose_name='gouvernorat')),
                ('fhir_resource_id', models.CharField(blank=True, help_text='ID de la ressource Patient sur le serveur HAPI FHIR', max_length=100, null=True, verbose_name='identifiant FHIR Patient')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
            ],
            options={
                'verbose_name': 'profil patient',
                'verbose_name_plural': 'profils patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='ReponseScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_soumission', models.CharField(choices=[('CAMPAGNE', 'Campagne de dépistage'), ('SOINS_PRIMAIRES', 'Centre de soins primaires'), ('AUTO_EVALUATION', 'Auto-évaluation citoyenne')], default='CAMPAGNE', max_length=30, verbose_name='type de soumission')),
                ('version_questionnaire', models.CharField(default='1.0', max_length=10, verbose_name='version du questionnaire')),
                ('donnees', models.JSONField(help_text='Réponses structurées aux 14 questions de dépistage', verbose_name='données du questionnaire')),
                ('soumis_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='soumis le')),
                ('fhir_resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='identifiant FHIR QuestionnaireResponse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_screening', to='screening.profilpatient', verbose_name='patient')),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings_soumis', to=settings.AUTH_USER_MODEL, verbose_name='soumis par')),
            ],
            options={
                'verbose_name': 'réponse de dépistage',
                'verbose_name_plural': 'réponses de dépistage',
                'ordering': ['-soumis_le'],
                'indexes': [models.Index(fields=['patient', '-soumis_le'], name='screening_r_patient_0fb762_idx'), models.Index(fields=['type_soumission'], name='screening_r_type_so_f5875b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='profilpatient',
            index=models.Index(fields=['ins'], name='screening_p_ins_d4549b_idx'),
        ),
        migrations.AddIndex(
            model_name='profilpatient',
            index=models.Index(fields=['gouvernorat'], name='screening_p_gouvern_48b342_idx'),
        ),
    ]
