# Generated by Django 4.2.16 on 2026-09-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpatient',
            name='cin',
            field=models.CharField(blank=True, db_index=True, help_text="Numéro CIN tunisien (8 chiffres) ou document d'identité", max_length=20, null=True, verbose_name='numéro CIN'),
        ),
        migrations.AddIndex(
            model_name='profilpatient',
            index=models.Index(fields=['cin', 'date_naissance'], name='screening_p_cin_99a09d_idx'),
        ),
    ]
