server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://hapi-fhir-db:5432/hapi_fhir
    username: hapi
    password: hapi_password
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
        search:
          default:
            backend: lucene
            directory:
              root: /var/lib/hapi/lucenefiles
    hibernate:
      ddl-auto: update

hapi:
  fhir:
    fhir_version: R4
    server_address: http://localhost:8080/fhir
    allow_external_references: true
    allow_multiple_delete: true
    reuse_cached_search_results_millis: 4000
    default_page_size: 20
    max_page_size: 100
    bulk_export_enabled: false
    narrative_enabled: false
