# Generated by Django 4.2.16 on 2026-09-24 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('ECHEC_CONNEXION', 'Échec de connexion'), ('CREATION_PATIENT', 'Création de profil patient'), ('CONSULTATION_PATIENT', 'Consultation dossier patient'), ('SOUMISSION_SCREENING', 'Soumission de dépistage'), ('EVALUATION_RISQUE', 'Évaluation de risque calculée'), ('VALIDATION_PLAN', 'Validation de plan de soin'), ('REJET_PLAN', 'Rejet de plan de soin'), ('MODIFICATION_PLAN', 'Modification de plan de soin'), ('PRISE_EN_CHARGE_TACHE', 'Prise en charge tâche'), ('CREATION_COMPTE', 'Création de compte'), ('MODIFICATION_COMPTE', 'Modification de compte'), ('SYNCHRONISATION_FHIR', 'Synchronisation FHIR')], max_length=50, verbose_name='action')),
                ('type_ressource', models.CharField(max_length=100, verbose_name='type de ressource')),
                ('id_ressource', models.CharField(blank=True, max_length=150, verbose_name='identifiant de la ressource')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='agent utilisateur')),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='horodatage')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='détails complémentaires')),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL, verbose_name='acteur')),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journaux d'audit",
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['action', 'horodatage'], name='audit_journ_action_871fa0_idx'), models.Index(fields=['type_ressource', 'id_ressource'], name='audit_journ_type_re_425c59_idx'), models.Index(fields=['acteur', 'horodatage'], name='audit_journ_acteur__b9e78e_idx')],
            },
        ),
    ]
