# Generated by Django 4.2.16 on 2026-09-24 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatEvaluationRisque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau_risque', models.CharField(choices=[('FAIBLE', 'Faible'), ('INTERMEDIAIRE', 'Intermédiaire'), ('ELEVE', 'Élevé')], db_index=True, max_length=20, verbose_name='niveau de risque')),
                ('score', models.IntegerField(help_text='Score normalisé entre 0 et 100', verbose_name='score de risque (0-100)')),
                ('facteurs', models.JSONField(default=list, help_text='Liste ordonnée des facteurs influençant le score', verbose_name='facteurs de risque contributifs')),
                ('version_moteur', models.CharField(default='stub-1.0', max_length=50, verbose_name='version du moteur de calcul')),
                ('evalue_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='évalué le')),
                ('fhir_resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='identifiant FHIR RiskAssessment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_risque', to='screening.profilpatient', verbose_name='patient')),
                ('reponse_screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_risque', to='screening.reponsescreening', verbose_name='réponse de dépistage associée')),
            ],
            options={
                'verbose_name': 'évaluation de risque',
                'verbose_name_plural': 'évaluations de risque',
                'ordering': ['-evalue_le'],
                'indexes': [models.Index(fields=['niveau_risque'], name='risk_engine_niveau__cf836a_idx'), models.Index(fields=['patient', '-evalue_le'], name='risk_engine_patient_f48725_idx')],
            },
        ),
    ]
