# Generated by Django 4.2.16 on 2026-09-24 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheNutritionniste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priorite', models.CharField(choices=[('STAT', 'Priorité maximale (Risque Élevé)'), ('URGENT', 'Urgent (Risque Intermédiaire)'), ('ROUTINE', 'Routine (Risque Faible)')], db_index=True, default='ROUTINE', max_length=20, verbose_name='priorité')),
                ('statut', models.CharField(choices=[('DEMANDE', 'En attente de prise en charge'), ('EN_COURS', 'En cours de traitement'), ('COMPLETE', 'Validé / Terminé'), ('REJETE', 'Rejeté')], db_index=True, default='DEMANDE', max_length=20, verbose_name='statut de la tâche')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('pris_en_charge_le', models.DateTimeField(blank=True, null=True, verbose_name='pris en charge le')),
                ('complete_le', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
                ('fhir_resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='identifiant FHIR Task')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='assigné à')),
                ('plan_soin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tache_nutritionniste', to='care_plan.plansoin', verbose_name='plan de soin associé')),
            ],
            options={
                'verbose_name': 'tâche nutritionniste',
                'verbose_name_plural': 'tâches nutritionnistes',
                'ordering': ['priorite', 'cree_le'],
                'indexes': [models.Index(fields=['statut', 'priorite', 'cree_le'], name='nutritionis_statut_aacaac_idx'), models.Index(fields=['assigne_a', 'statut'], name='nutritionis_assigne_4b0b5d_idx')],
            },
        ),
    ]
