# Generated by Django 4.2.16 on 2026-09-24 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteUtilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='identifiant')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('role', models.CharField(choices=[('AGENT_CAMPAGNE', 'Agent de campagne'), ('AGENT_SOINS_PRIMAIRES', 'Agent de soins primaires'), ('NUTRITIONNISTE', 'Nutritionniste'), ('ADMIN_MINISTERE', 'Administrateur Ministère'), ('ADMIN_IT', 'Administrateur IT'), ('CITOYEN', 'Citoyen')], default='CITOYEN', max_length=30, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès administration')),
                ('expire_le', models.DateTimeField(blank=True, help_text='Laisser vide pour un compte permanent. Obligatoire pour les agents de campagne.', null=True, verbose_name="date d'expiration")),
                ('gouvernorat', models.CharField(blank=True, help_text="Gouvernorat d'affectation (agents uniquement)", max_length=100, verbose_name='gouvernorat')),
                ('fhir_practitioner_id', models.CharField(blank=True, help_text='Rempli automatiquement lors de la synchronisation FHIR', max_length=100, null=True, verbose_name='identifiant FHIR Practitioner')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('derniere_connexion_le', models.DateTimeField(blank=True, null=True, verbose_name='dernière connexion')),
                ('mot_de_passe_temporaire', models.BooleanField(default=False, help_text="Si vrai, l'utilisateur doit changer son mot de passe à la prochaine connexion", verbose_name='mot de passe temporaire')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'compte utilisateur',
                'verbose_name_plural': 'comptes utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('PLAN_VALIDE', 'Plan validé'), ('PLAN_REJETE', 'Plan rejeté'), ('RAPPEL_AUTO_EVALUATION', 'Rappel auto-évaluation'), ('COMPTE_EXPIRE_BIENTOT', 'Compte bientôt expiré')], max_length=30, verbose_name='type')),
                ('message', models.TextField(verbose_name='message')),
                ('lu', models.BooleanField(default=False, verbose_name='lu')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('lu_le', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['destinataire', 'lu'], name='accounts_no_destina_778f38_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='compteutilisateur',
            index=models.Index(fields=['role'], name='accounts_co_role_5799a3_idx'),
        ),
        migrations.AddIndex(
            model_name='compteutilisateur',
            index=models.Index(fields=['is_active', 'expire_le'], name='accounts_co_is_acti_a69fb3_idx'),
        ),
    ]
