# Generated by Django 4.2.16 on 2026-09-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteutilisateur',
            name='campagne_date_fin',
            field=models.DateField(blank=True, help_text='Date de fin de validité opérationnelle de la campagne', null=True, verbose_name='date de fin de campagne'),
        ),
        migrations.AddField(
            model_name='compteutilisateur',
            name='responsable_structure',
            field=models.CharField(blank=True, help_text='Médecin chef de centre ou coordinateur de campagne', max_length=100, verbose_name='responsable structure'),
        ),
        migrations.AddField(
            model_name='compteutilisateur',
            name='structure_code',
            field=models.CharField(blank=True, help_text='Code CSB ou identifiant de caravane', max_length=50, verbose_name='code structure'),
        ),
        migrations.AddField(
            model_name='compteutilisateur',
            name='structure_localisation',
            field=models.CharField(blank=True, help_text="Délégation, ville ou adresse d'intervention", max_length=200, verbose_name='localisation de la structure'),
        ),
        migrations.AddField(
            model_name='compteutilisateur',
            name='structure_nom',
            field=models.CharField(blank=True, help_text='Nom du dispensaire/CSB ou de la campagne mobile', max_length=150, verbose_name='nom de la structure'),
        ),
    ]
