"""
demo_profiles.py — Profils cliniques types pour le moteur de risque et protocoles WiQayati.
"""

KARIM = {
    "age": 56,
    "sex": "M",
    "pregnant": False,
    "known_diabetes": False,
    "weight_kg": 92.0,
    "height_cm": 174.0,
    "bmi": 30.4,
    "waist_cm": 104.0,
    "active_30min_daily": False,
    "veg_fruit_daily": False,
    "bp_medication": True,
    "high_glucose_ever": True,
    "family_history": "first_degree",
    "sbp": 158.0,
    "hypertension_dx": True,
    "smoker_now": True,
    "gestational_dm": False,
    "glucose_mgdl": 115.0,
    "glucose_fasting": True,
    "hba1c_pct": None,
    "symptoms": ["fatigue", "nycturie"],
    "statut_tabagisme": "FUMEUR_ACTUEL",
    "qualite_alimentation": "MAUVAISE",
    "niveau_activite_physique": "FAIBLE",
    "allergie_alimentaire": "",
}

LEILA = {
    "age": 48,
    "sex": "F",
    "pregnant": False,
    "known_diabetes": False,
    "weight_kg": 78.0,
    "height_cm": 162.0,
    "bmi": 29.7,
    "waist_cm": 92.0,
    "active_30min_daily": False,
    "veg_fruit_daily": True,
    "bp_medication": False,
    "high_glucose_ever": False,
    "family_history": "second_degree",
    "sbp": 128.0,
    "hypertension_dx": False,
    "smoker_now": False,
    "gestational_dm": False,
    "glucose_mgdl": 98.0,
    "glucose_fasting": True,
    "hba1c_pct": None,
    "symptoms": [],
    "statut_tabagisme": "JAMAIS",
    "qualite_alimentation": "MOYENNE",
    "niveau_activite_physique": "FAIBLE",
    "allergie_alimentaire": "arachides",
}

AMIRA = {
    "age": 34,
    "sex": "F",
    "pregnant": False,
    "known_diabetes": False,
    "weight_kg": 68.0,
    "height_cm": 165.0,
    "bmi": 25.0,
    "waist_cm": 82.0,
    "active_30min_daily": True,
    "veg_fruit_daily": True,
    "bp_medication": False,
    "high_glucose_ever": False,
    "family_history": "none",
    "sbp": 118.0,
    "hypertension_dx": False,
    "smoker_now": False,
    "gestational_dm": True,
    "glucose_mgdl": 92.0,
    "glucose_fasting": True,
    "hba1c_pct": None,
    "symptoms": [],
    "statut_tabagisme": "JAMAIS",
    "qualite_alimentation": "BONNE",
    "niveau_activite_physique": "MODERE",
    "allergie_alimentaire": "",
}
