# Generated by Django 4.2.16 on 2026-09-24 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSyncFhir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_ressource', models.CharField(max_length=50, verbose_name='type de ressource FHIR')),
                ('id_local', models.CharField(max_length=100, verbose_name='identifiant local de la ressource')),
                ('fhir_id', models.CharField(blank=True, max_length=100, verbose_name='identifiant FHIR distant')),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('EN_ATTENTE', 'En attente de nouvelle tentative')], default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('tentatives', models.IntegerField(default=0, verbose_name='nombre de tentatives')),
                ('dernier_message_erreur', models.TextField(blank=True, verbose_name="dernier message d'erreur")),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'journal de synchronisation FHIR',
                'verbose_name_plural': 'journaux de synchronisation FHIR',
                'ordering': ['-cree_le'],
            },
        ),
    ]
